// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonlightTelemetry.App.Database;

#nullable disable

namespace MoonlightTelemetry.App.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230706234331_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MoonlightTelemetry.App.Database.Entities.Moonlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Databases")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Nodes")
                        .HasColumnType("int");

                    b.Property<int>("Servers")
                        .HasColumnType("int");

                    b.Property<int>("Users")
                        .HasColumnType("int");

                    b.Property<int>("Webspaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Moonlights");
                });
#pragma warning restore 612, 618
        }
    }
}
